name: Front CI

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - "front/**"
      - ".github/workflows/front.yml"
  push:
    branches: ["main"]
    paths:
      - "front/**"
      - ".github/workflows/front.yml"
defaults:
  run:
    working-directory: front/App_front

env:
  NODE_VERSION: "23.10.0"
  PNPM_VERSION: "10.13.1"
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm@${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm@${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install

      - run: pnpm lint
        env:
          DEBUG_MESSAGE: ${{ env.DEBUG_MESSAGE }}
