name: Front CI

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - "front/**"
      - ".github/workflows/front.yml"
  push:
    branches: ["main"]
    paths:
      - "front/**"
      - ".github/workflows/front.yml"
defaults:
  run:
    working-directory: front/App_front

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - run: pwd ls -la echo "テストだよ!!"
